In [67]:
import numpy as np
import pylab as pl
import scipy as sc
from datetime import datetime
%matplotlib notebook 

directory = './Measurements/'
filenames = ["GPSLog"]
mat = []
l_date = []
l_time = []
for dataset in range(len(filenames)):
    print(filenames[dataset])
    gps_file = open(filenames[dataset], "r")
    # mat = np.loadtxt(directory+filenames[dataset]) #change for loop
    for line in gps_file:
        date, time, long, lat, *alt = line.split()
        l_date.append(date)
        l_time.append(time)
        mat.append([float(long),float(lat),float(alt[0] if (len(alt) > 0)else 0)])
mat = np.array(mat)
print(mat)

GPSLog
[[ 49.4497014  11.8392176   0.       ]
 [ 49.4497325  11.8392308   0.       ]
 [ 49.4497412  11.8392351   0.       ]
 ...
 [ 49.4497262  11.8391375 457.6000061]
 [ 49.4497258  11.8391386 457.6000061]
 [ 49.4497249  11.8391435 457.6000061]]


In [90]:
timestamps = []
l_frequency = []
for k,dates in enumerate(l_date):
    timestamps.append(datetime.strptime(l_date[k]+' '+l_time[k], '%d.%m.%y %H:%M:%S:%f'))
    if len(timestamps) > 1:
        delta = timestamps[k]-timestamps[k-1]
        l_frequency.append(1/abs(float(delta.total_seconds())) if float(delta.total_seconds()) != 0 else 0)
    if len(timestamps) == 2:
        l_frequency.append(1/abs(float(delta.total_seconds())) if float(delta.total_seconds()) != 0 else 0)

print('Frequency Mean Value: ',np.mean(l_frequency))

Frequency Mean Value:  2.318447912217643
